version: 2
jobs:
  build:
    docker:
      - image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/ecr-ci:1.0.3
        aws_auth:
          aws_access_key_id: $AWS_ACCESS_KEY_ID
          aws_secret_access_key: $AWS_SECRET_ACCESS_KEY
    working_directory: /go/src/github.com/johndistasio/responder
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build Docker Image
          command: |
            docker build -t terraform-ci .
      - run:
          name: Push Docker Image
          command: |
            GIT_REV="$(git rev-parse --short HEAD)"
            GIT_TAG="$(git describe --tags --always)"
            $(aws ecr get-login --no-include-email)
            docker tag terraform-ci $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/responder:$GIT_REV
            docker tag terraform-ci $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/responder:$GIT_TAG
            docker tag terraform-ci $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/responder:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/responder:$GIT_REV
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/responder:$GIT_TAG
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/responder:latest

workflows:
  version: 2
  build:
    jobs:
      - build:
          context: AWS
          filters:
            branches:
              only:
                - master
            tags:
              only:
                - /^.+/
